apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  groups:
    - name: {{ .Values.groupName }}
      rules:
        - alert: {{ .Values.alertName }}
          expr: {{ .Values.expr }}
          for: {{ .Values.duration }}
          labels:
      {{ if ne (toString .Values.labels.team) "nil" }}
            team: {{ .Values.labels.team }}
      {{ end }}
      {{ if ne (toString .Values.labels.component) "nil" }}
            component: {{ .Values.labels.component }}
      {{ end }}
            alertname: {{ .Values.alertName }}
            namespace: {{ .Release.Namespace }}
          annotations:
            description: {{ .Values.description }}
